import unittest

from test_grammar import TestGrammar
from test_interpreter import TestInterpreter
from test_type_system_classes import TestTypeSystemClasses
from test_type_system_parser import TestTypeSystemParser
from type_compat_checker import TestTypeCompatibilityChecker
from test_typecore import TestTypeCore

unittest.main()